import {makeDeck,type Question} from './questions';
export type Player={id:string;token:string;name:string;score:number;correct:number;ready:boolean};
type Answer={choice:number;points:number;elapsed:number};
export type Game={host:string;players:Player[];phase:'lobby'|'question'|'reveal'|'finished'|'closed';deck:Question[];round:number;start:number;answers:Record<string,Answer>;match:number};
export class GameError extends Error {constructor(message:string,public status=400){super(message)}}
export function player(name:unknown):Player {if(typeof name!=='string'||!name.trim()||name.trim().length>20)throw new GameError('Enter a name between 1 and 20 characters.');return {id:crypto.randomUUID(),token:crypto.randomUUID(),name:name.trim(),score:0,correct:0,ready:false}}
export function newGame(p:Player):Game{return {host:p.id,players:[p],phase:'lobby',deck:[],round:0,start:0,answers:{},match:1}}
export function points(elapsed:number){return 100+Math.round(50*Math.max(0,1-Math.max(0,elapsed)/15000))}
export function settle(g:Game,now:number){if(g.phase==='question'&&(now>=g.start+15000||(now>=g.start&&g.players.every(p=>g.answers[p.id])))){g.phase='reveal';for(const p of g.players){const a=g.answers[p.id];if(a){p.score+=a.points;if(a.points>0)p.correct++}}return true}return false}
export function act(g:Game,actor:Player,action:string,input:Record<string,unknown>,now:number){
 const host=actor.id===g.host;
 if(action==='ready'){if(g.phase!=='lobby')throw new GameError('The match has already started.');actor.ready=!actor.ready;return}
 if(action==='leave'){if(g.phase!=='lobby'&&g.phase!=='finished')throw new GameError('Stay in the room until the match ends. You can reconnect by reopening this tab.');g.players=g.players.filter(p=>p.id!==actor.id);if(host){if(g.players.length)g.host=g.players[0].id;else g.phase='closed'}return}
 if(action==='start'){if(!host)throw new GameError('Only the host can start.',403);if(g.phase!=='lobby')throw new GameError('The match is already underway.');if(g.players.length<2||!g.players.every(p=>p.ready))throw new GameError('At least two players must join, and everyone must be ready.');g.deck=makeDeck();g.round=0;g.answers={};g.start=now+4000;g.phase='question';return}
 if(action==='answer'){if(g.phase!=='question'||input.round!==g.round||input.match!==g.match||now<g.start||now>=g.start+15000)throw new GameError('This round is not accepting answers.');if(g.answers[actor.id])throw new GameError('Your answer is already locked.');if(!Number.isInteger(input.choice)||Number(input.choice)<0||Number(input.choice)>3)throw new GameError('Choose one of the four answers.');const choice=Number(input.choice);const elapsed=now-g.start;g.answers[actor.id]={choice,elapsed,points:g.deck[g.round].options[choice]===g.deck[g.round].answer?points(elapsed):0};settle(g,now);return}
 if(action==='next'){if(!host)throw new GameError('Only the host can advance.',403);if(g.phase!=='reveal'||input.round!==g.round||input.match!==g.match)throw new GameError('Wait for the round to finish.');if(g.round===11){g.phase='finished';return}g.round++;g.answers={};g.start=now+4000;g.phase='question';return}
 if(action==='rematch'){if(!host||g.phase!=='finished')throw new GameError('The host can start a rematch after the results.');g.phase='lobby';g.deck=[];g.round=0;g.answers={};g.match++;g.players.forEach(p=>{p.score=0;p.correct=0;p.ready=false});return}
 throw new GameError('Unknown action.');
}
export function view(g:Game,me:Player,code:string,now:number){const revealing=g.phase==='reveal'||g.phase==='finished';const q=g.deck[g.round];const started=now>=g.start;return {code,host:g.host,me:me.id,phase:g.phase,round:g.round,match:g.match,start:g.start,serverTime:now,answered:Object.keys(g.answers).length,mine:g.answers[me.id]?{choice:g.answers[me.id].choice,...(revealing?g.answers[me.id]:{})}:null,players:g.players.map(({token,...p})=>({...p,answered:!!g.answers[p.id],...(revealing?{roundPoints:g.answers[p.id]?.points??0}:{})})),question:q?{category:q.category,...(started||revealing?{prompt:q.prompt,options:q.options}:{}),...(revealing?{answer:q.answer,reference:q.reference,explanation:q.explanation}:{})}:null}}
