// Server-only question bank. Never import this module into the client.
export const categories=['Who Am I?','What Happened First?','Finish the Verse','Bible Facts','Bible Story, Badly Explained','Biblical Group Chat'];
export type Question={id:string;category:number;prompt:string;options:string[];answer:string;reference:string;explanation:string};
const rows:[number,string,string,string[],string,string][]=[
[0,'I sold purple goods in Philippi and welcomed Paul and his companions into my home. Who am I?','Lydia',['Priscilla','Phoebe','Dorcas'],'Acts 16:14–15','Lydia was a seller of purple goods from Thyatira. After her household was baptized, she offered hospitality to Paul and his companions.'],
[0,'I was a tentmaker, married to Priscilla, and helped explain the way of God more accurately to Apollos.','Aquila',['Silas','Barnabas','Titus'],'Acts 18:2–3, 26','Aquila and Priscilla shared Paul’s trade and later helped Apollos deepen his understanding.'],
[0,'I requested letters from the king, inspected ruined walls at night, and organized their rebuilding.','Nehemiah',['Ezra','Zerubbabel','Josiah'],'Nehemiah 2:7–18','Nehemiah served as the king’s cupbearer before traveling to Jerusalem to lead the rebuilding of its walls.'],
[0,'I was a judge and prophetess who summoned Barak to lead an army.','Deborah',['Miriam','Huldah','Abigail'],'Judges 4:4–9','Deborah judged Israel and called Barak to gather troops. She agreed to accompany him.'],
[1,'Which of these events happened first?','Joseph is sold by his brothers',['Moses leads Israel out of Egypt','Joshua leads Israel across the Jordan','David becomes king'],'Genesis 37; Exodus 12; Joshua 3; 2 Samuel 5','Joseph’s sale precedes Israel’s time in Egypt, the exodus, the entry into Canaan, and the monarchy.'],
[1,'Which event in David’s life happened first?','Samuel anoints David',['David defeats Goliath','David becomes king of all Israel','David brings the ark to Jerusalem'],'1 Samuel 16–17; 2 Samuel 5–6','Samuel anointed David while Saul was still king, before David’s encounter with Goliath.'],
[1,'Which of these events happened first?','The birth of Jesus',['Jesus is baptized','The transfiguration','Jesus enters Jerusalem on a donkey'],'Luke 2–3; Luke 9:28–36; Luke 19:28–40','Jesus’ birth comes before his adult baptism and public ministry, including the transfiguration and entry into Jerusalem.'],
[1,'Which event in Acts happened first?','The Holy Spirit comes at Pentecost',['Stephen is killed','Saul encounters Jesus on the Damascus road','Paul and Silas are imprisoned in Philippi'],'Acts 2; 7; 9; 16','Pentecost occurs in Acts 2, before Stephen’s death, Saul’s conversion, and Paul’s later missionary journeys.'],
[2,'Complete this ESV excerpt: “Trust in the LORD with all your _____”','heart',['strength','mind','soul'],'Proverbs 3:5','The verse calls for wholehearted trust in the Lord rather than reliance on our own understanding.'],
[2,'Complete this ESV excerpt: “Your word is a _____ to my feet”','lamp',['guide','fire','light'],'Psalm 119:105','The psalmist pictures God’s word as a lamp to the feet and a light to the path.'],
[2,'Complete this ESV excerpt: “let every person be quick to hear, slow to _____”','speak',['judge','answer','act'],'James 1:19','James urges readiness to listen, restraint in speaking, and slowness to anger.'],
[2,'Complete this ESV excerpt: “walk _____ with your God”','humbly',['boldly','faithfully','quietly'],'Micah 6:8','Micah connects humble walking with God to doing justice and loving kindness.'],
[3,'Who was chosen to take Judas’s place among the apostles?','Matthias',['Barnabas','Stephen','Apollos'],'Acts 1:23–26','Joseph called Barsabbas and Matthias were proposed. After prayer and casting lots, Matthias was chosen.'],
[3,'On which island was Paul shipwrecked on his journey toward Rome?','Malta',['Crete','Cyprus','Patmos'],'Acts 28:1','After everyone reached shore safely, they learned the island was called Malta. The islanders welcomed them.'],
[3,'Which prophet confronted David after his sin involving Bathsheba and Uriah?','Nathan',['Samuel','Gad','Elijah'],'2 Samuel 12:1–13','Nathan told David a story about a rich man taking a poor man’s lamb, then exposed David’s wrongdoing.'],
[3,'At the wedding in Cana, how many stone water jars are mentioned?','Six',['Three','Seven','Twelve'],'John 2:6','John describes six stone water jars used for Jewish purification rites. Jesus instructed the servants to fill them.'],
[4,'Identify the story: A runaway’s travel itinerary includes an unexpected three-night stay inside a fish.','Jonah flees God’s call',['Paul is shipwrecked','Peter walks on water','Moses crosses the Red Sea'],'Jonah 1:1–17','Jonah boarded a ship away from his assignment to Nineveh. After he was thrown into the sea, the Lord appointed a great fish to swallow him.'],
[4,'Identify the story: A very short man discovers that the best seat for a passing crowd is technically a tree.','Zacchaeus meets Jesus',['Nicodemus visits Jesus','Philip meets the Ethiopian official','Bartimaeus calls to Jesus'],'Luke 19:1–10','Zacchaeus climbed a sycamore tree to see Jesus over the crowd. Jesus called him down and stayed at his house.'],
[4,'Identify the story: A roofing project nobody requested becomes the fastest route to a healing appointment.','Friends lower a paralyzed man to Jesus',['Peter heals a man at the temple','Jesus heals ten lepers','Elisha heals Naaman'],'Mark 2:1–12','Unable to get through the crowd, the man’s friends opened the roof and lowered his bed to Jesus.'],
[4,'Identify the story: A late-night sermon becomes an emergency rescue after someone chooses a window seat.','Eutychus falls during Paul’s talk',['Peter escapes from prison','Jesus calms the storm','Stephen addresses the council'],'Acts 20:7–12','Eutychus fell asleep during Paul’s long talk and fell from a third-story window. Paul went down to him, and he was brought away alive.'],
[5,'Which story fits this invented chat?\nFriend 1: The front door is hopeless.\nFriend 2: How attached are they to this roof?\nFriend 3: Keep the bed level.','A paralyzed man is lowered to Jesus',['Noah builds the ark','Nehemiah rebuilds the walls','Peter visits Cornelius'],'Mark 2:1–12','The friends reached Jesus by opening the roof and lowering the man on his bed. This chat is invented, not Scripture.'],
[5,'Which story fits this invented chat?\nServant: We have a beverage problem.\nAnother servant: These jars are full of water.\nSteward: Why did you save the best until now?','The wedding at Cana',['The feeding of the five thousand','The Last Supper','Elijah visits the widow'],'John 2:1–11','At Cana, Jesus turned water into wine. The master of the feast remarked on the good wine being served later. This chat is invented.'],
[5,'Which story fits this invented chat?\nBuilder 1: Pass another brick.\nBuilder 2: I have no idea what you just said.\nBuilder 3: This project suddenly needs translators.','The tower of Babel',['Solomon builds the temple','Nehemiah repairs Jerusalem','Noah builds the ark'],'Genesis 11:1–9','At Babel, God confused the people’s language and dispersed them. This fictional exchange imagines the communication breakdown.'],
[5,'Which story fits this invented chat?\nSoldier: We are marching again?\nAnother soldier: Yes. Bring your trumpet.\nSoldier: Unusual siege equipment, but all right.','The fall of Jericho',['Gideon defeats Midian','David defeats Goliath','Saul searches for donkeys'],'Joshua 6:1–20','Israel marched around Jericho as instructed. Priests blew trumpets, the people shouted, and the walls fell. The dialogue is invented.']
];
export const questions:Question[]=rows.map((r,i)=>({id:`q${i+1}`,category:r[0],prompt:r[1],answer:r[2],options:[r[2],...r[3]],reference:r[4],explanation:r[5]}));
export function shuffle<T>(list:T[]):T[]{const a=[...list];for(let i=a.length-1;i>0;i--){const n=new Uint32Array(1);crypto.getRandomValues(n);const j=n[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
export function makeDeck(){return shuffle(categories.flatMap((_,c)=>shuffle(questions.filter(q=>q.category===c)).slice(0,2))).map(q=>({...q,options:shuffle(q.options)}))}
